-- Script d'importation massif des clients rectifié avec structure complète
-- Colonnes : first_name, last_name, address, gps_lat, gps_lng, phone, email, city

INSERT INTO clients (first_name, last_name, address, gps_lat, gps_lng, phone, email, city) VALUES
('Med kacem', 'unitec', 'Clinique amen', NULL, NULL, NULL, NULL, NULL),
('Med', 'nakkach', 'Morneg', NULL, NULL, NULL, NULL, NULL),
('Med', 'awnallah', NULL, NULL, NULL, NULL, NULL, NULL),
('Farid', 'tanfous', 'Bni kiar', NULL, NULL, NULL, NULL, 'Nabeul'),
('Nawfel ben kdija', 'unitec', 'Klibia', NULL, NULL, NULL, NULL, NULL),
('Afef', 'unitec', 'Menzel Temime, Tunisie', NULL, NULL, NULL, NULL, NULL),
('Walid', 'sassi', 'Afh', NULL, NULL, NULL, NULL, NULL),
('Marouen', 'chawachi', 'Africa djade korba', NULL, NULL, NULL, NULL, NULL),
('Immobilier', '81', 'Bp 224 Hammamet Nord, Hammamet 8050, Tunisie', NULL, NULL, NULL, NULL, NULL),
('Ayachi amor', 'ben slimen', 'Resident jannet Hammamet', NULL, NULL, NULL, NULL, NULL),
('Nabil swissi', 'unitec', NULL, NULL, NULL, NULL, NULL, NULL),
('Am', 'Salah', 'Karrouba', NULL, NULL, NULL, NULL, NULL),
('Med', 'ayyat', 'Nabeul', NULL, NULL, NULL, NULL, NULL),
('Ramzi', 'trabelsi', 'Sidi Slimane', NULL, NULL, NULL, NULL, NULL),
('Mounir', 'nakka3', NULL, NULL, NULL, NULL, NULL, NULL),
('Kamel rassil', 'hichem', 'Jinen Hammamet', NULL, NULL, NULL, NULL, NULL),
('Sahbi', 'ben salha', 'In kmicha', NULL, NULL, NULL, NULL, NULL),
('Monsef', 'mbarek fils', 'Tunis', NULL, NULL, NULL, NULL, NULL),
('Bouraoui', 'zaanouni', 'Dar Allouche, Tunisie', NULL, NULL, NULL, NULL, NULL),
('Imed Slimani', 'unitec', 'Hammamet, Tunisie', NULL, NULL, NULL, NULL, NULL),
('Khaled', 'kmakhem', 'Besbasia', NULL, NULL, NULL, NULL, NULL),
('Med', 'kalfat', 'Rue de, Beni Khiar 8060, Tunisie', NULL, NULL, NULL, NULL, NULL),
('Fraj', 'maatouk', 'Lac', 36.835583, 10.235252, NULL, NULL, NULL),
('Amin', 'abid', 'Dar Chabanne', NULL, NULL, NULL, NULL, NULL),
('Radwen', 'unitec', 'Manuel bouzelfa', NULL, NULL, NULL, NULL, NULL),
('Sahbi', 'gannouchi', 'Hammamet', NULL, NULL, NULL, NULL, NULL),
('Achref', 'unitec', 'Sidi hammed', NULL, NULL, NULL, NULL, NULL),
('Sihem', 'abed', 'Afh Nabeul', NULL, NULL, NULL, NULL, NULL),
('Zin hadded', 'unitec', 'Kraksi', 36.457781, 10.754448, NULL, NULL, NULL),
('Nabil', 'marsit', 'Hammamet Sud, Tunisie', NULL, NULL, NULL, NULL, NULL),
('Fawsi', 'rafik', 'Resident jannet', NULL, NULL, NULL, NULL, NULL),
('Karim', 'jmaa', 'Somaa Nabeul', NULL, NULL, NULL, NULL, NULL),
('Barhoumi', 'unitec', 'Karrouba', NULL, NULL, NULL, NULL, NULL),
('Amin daklaoui', 'unitec', 'Bnikhiar', NULL, NULL, NULL, NULL, NULL),
('Mm', 'rayes', 'Daroufa', NULL, NULL, NULL, NULL, NULL),
('Nawfel', 'gabsi', 'Dar allouche', NULL, NULL, NULL, NULL, NULL),
('Kais', 'bni kiar', 'Bnikhiar', NULL, NULL, NULL, NULL, NULL),
('Ali', 'mrad', 'unitec', NULL, NULL, NULL, NULL, 'Jinen bnikhiar'),
('Hassen', 'Sallami', 'Daroufa', NULL, NULL, NULL, NULL, NULL),
('Kamel', 'unitec', 'Nahrawes', NULL, NULL, NULL, NULL, NULL),
('Amin', 'negzaoui', 'Hanchir kort', NULL, NULL, NULL, NULL, NULL),
('Sirine', NULL, 'Terrin romaine', NULL, NULL, NULL, NULL, NULL),
('Midis', NULL, 'In kmicha', NULL, NULL, NULL, NULL, NULL),
('Med', 'rtiba', 'Rtiba', NULL, NULL, NULL, NULL, NULL),
('Makrem', 'karbech', 'Afh', NULL, NULL, NULL, NULL, NULL),
('Mahdi', 'Sfia', 'Nabeul', NULL, NULL, NULL, NULL, NULL),
('Haïfa hichri', 'unitec', 'Daroufa', NULL, NULL, NULL, NULL, NULL),
('Habib', 'unitec', 'Afh', NULL, NULL, NULL, NULL, NULL),
('Nahla', 'unitec', 'Bnikhiar', NULL, NULL, NULL, NULL, NULL),
('Ritha', 'ben salem', 'Korba', NULL, NULL, NULL, NULL, NULL),
('Amine', 'fatal', 'Hawaria nabeul', NULL, NULL, NULL, NULL, NULL),
('Oussama sbai', 'unitec', NULL, NULL, NULL, NULL, NULL, NULL),
('John', 'sidi Slimane', 'Sidi Slimane', NULL, NULL, NULL, NULL, NULL),
('Mourad', 'bouchnak', 'Hammamet sud', NULL, NULL, NULL, NULL, NULL),
('Idéal', 'école', 'Lido', NULL, NULL, NULL, NULL, NULL),
('Ben Arbia', 'unitec', 'Wed souhil', NULL, NULL, NULL, NULL, NULL),
('Hichem', 'dhen', 'Kiops', NULL, NULL, NULL, NULL, NULL),
('Lotfi', 'monchar', 'Monchar', NULL, NULL, NULL, NULL, NULL),
('Ritha', 'abid', 'Ma3moura', NULL, NULL, NULL, NULL, NULL),
('Hechmi', 'immo 81', 'Nahrawes', NULL, NULL, NULL, NULL, NULL),
('Med Saied', 'lotfi', 'Lebhar', NULL, NULL, NULL, NULL, NULL),
('Michelle', NULL, 'Sidi slimene', NULL, NULL, NULL, NULL, NULL),
('Hatem', 'lousaief', 'Bir challouf', NULL, NULL, NULL, NULL, NULL),
('Hamed', 'younes', 'Daroufa', NULL, NULL, NULL, NULL, NULL),
('Tarak', 'maala', 'Hammamet', NULL, NULL, NULL, NULL, NULL),
('Sidi Mohamed', 'tziri', 'Mahersi', NULL, NULL, '54887800', NULL, NULL),
('Zangar', NULL, 'Lido', 36.452810, 10.752903, NULL, NULL, NULL),
('Boujbel', 'unitec', 'Yesmine Hammamet', NULL, NULL, NULL, NULL, NULL),
('Jlassi', NULL, 'Yesmine Hammamet', NULL, NULL, NULL, NULL, NULL),
('Rawtha garbi', 'unitec', 'Mrezga', NULL, NULL, NULL, NULL, NULL),
('Samir', 'tziri', 'Kraksi', NULL, NULL, NULL, NULL, NULL),
('Skandar', 'sakka', 'Terrin rommene', NULL, NULL, '50536031', NULL, NULL),
('Slim chelli', 'unitec', 'Birchalouf', NULL, NULL, NULL, NULL, NULL),
('Choukri', 'arfaoui', 'Mahersi', NULL, NULL, NULL, NULL, NULL),
('Rachel', 'fray', 'Jasmin', NULL, NULL, NULL, NULL, NULL),
('Lasaad', 'kaak', 'Hammamet, Tunisie', NULL, NULL, NULL, NULL, NULL),
('Abd jabbar', 'unitec', 'Gardaya', NULL, NULL, NULL, NULL, NULL),
('Mansour sassi', 'unitec', 'El Kharrouba, Algérie', NULL, NULL, NULL, NULL, NULL),
('Amin', 'amigos', 'Kawnia', NULL, NULL, NULL, NULL, NULL),
('Mohamed trabelsi', 'unitec', 'Menzel Bou Zelfa, Tunisie', NULL, NULL, NULL, NULL, NULL),
('Wafa', NULL, 'Afh', NULL, NULL, NULL, NULL, NULL),
('Mkadmi', NULL, 'Kraksi', NULL, NULL, NULL, NULL, NULL),
('Hsiki', 'Ahmed', 'Fac de langue', NULL, NULL, NULL, NULL, NULL),
('Granne', NULL, NULL, 36.455170, 10.748145, NULL, NULL, 'Nabeul'),
('Halleb', 'docteur', 'Jusmin', NULL, NULL, NULL, NULL, NULL),
('Mourad', 'galleb', 'Bnikhiar', NULL, NULL, NULL, NULL, NULL),
('Naana3', 'ma3moura', 'Ma3moura', NULL, NULL, NULL, NULL, NULL),
('Wael', 'ezzine', NULL, NULL, NULL, NULL, NULL, NULL),
('Adel', 'ben ahmed', NULL, NULL, NULL, NULL, NULL, NULL),
('Walid sassi', '2', 'Afh', NULL, NULL, NULL, NULL, NULL),
('Souraya bahroun', 'unitec', 'Mahersi', NULL, NULL, NULL, NULL, NULL),
('Salwa lajri', 'saied', 'Bouachir, Aït Khellili, Algérie', NULL, NULL, '23558502', NULL, NULL),
('Walid', 'chmengui', 'Hammamet, Tunisie', NULL, NULL, '98768004', NULL, NULL),
('Gassen', 'elbir', 'Nabeul', NULL, NULL, NULL, NULL, NULL),
('Mourad sezar', 'unitec', 'Sidi hammed', NULL, NULL, NULL, NULL, NULL),
('Saber', 'trabelsi', 'Cité Moura', NULL, NULL, NULL, NULL, NULL),
('Monji masoudi', 'unitec', 'Nahrawes', NULL, NULL, NULL, NULL, NULL),
('Haj Kacem', 'modial', NULL, NULL, NULL, '24294222', NULL, NULL),
('Mokhtar', 'lousaief', 'Birchalouf', NULL, NULL, NULL, NULL, NULL),
('Jaber', 'location', 'Centure', NULL, NULL, NULL, NULL, NULL),
('Marouen', 'mrabet', 'Bnikhiar', NULL, NULL, NULL, NULL, NULL),
('Rchid', 'saddadi', 'Mahersi', NULL, NULL, NULL, NULL, NULL),
('Résidence turkoise', 'unitec', 'Afh', NULL, NULL, NULL, NULL, NULL),
('Sana', 'makhlouf', 'Manzel bouzelfa', NULL, NULL, NULL, NULL, NULL),
('Ahmed', 'smail', 'Bnikhiar', NULL, NULL, NULL, NULL, NULL),
('Nizar', 'lido', 'Lido', NULL, NULL, NULL, NULL, NULL),
('Mahdi', 'ezzine', 'Club Med', NULL, NULL, NULL, NULL, NULL),
('Mariem boujbel', 'unitec', 'Jinen Hammamet', NULL, NULL, NULL, NULL, NULL),
('Amin', 'bellalah', 'Afh Nabeul', NULL, NULL, NULL, NULL, NULL),
('Med saheb', 'liesse', 'Bnikhiar', NULL, NULL, NULL, NULL, NULL),
('Med Ali', 'kaak', 'Afh mrezga', NULL, NULL, NULL, NULL, NULL),
('Habib', 'ben romthan', 'Hammamet', NULL, NULL, NULL, NULL, NULL),
('Jawher', 'thaw', 'Africajad', NULL, NULL, NULL, NULL, NULL),
('Sami', 'mami', 'Hôtels Zenith', NULL, NULL, '29058058', NULL, NULL),
('Hager', 'Walid', 'Centure', NULL, NULL, NULL, NULL, NULL),
('Bachrouch', NULL, 'Mrezga', NULL, NULL, NULL, NULL, NULL),
('Jawher dangir', 'unitec', 'Mrezga', NULL, NULL, NULL, NULL, NULL),
('Heni', 'amis', 'Korba', NULL, NULL, NULL, NULL, NULL),
('Sable argentée', NULL, 'Bnikhiar', NULL, NULL, NULL, NULL, NULL),
('rached', 'unitec', NULL, NULL, NULL, '26707551', NULL, NULL),
('Monsef', 'mbarek', 'Ma3moura', NULL, NULL, NULL, NULL, NULL),
('Imed', 'tazarka', 'Tazarka', NULL, NULL, NULL, NULL, NULL),
('Elboukari', NULL, 'Mahersi', NULL, NULL, NULL, NULL, NULL),
('Aziz', 'ayed', 'Mahersi', NULL, NULL, NULL, NULL, NULL),
('Hela', 'naana3', 'Afh', NULL, NULL, NULL, NULL, NULL),
('Imed ib', 'ib', 'Hammamet sud', NULL, NULL, NULL, NULL, NULL),
('Sami', 'dridi', 'Hammamet', NULL, NULL, NULL, NULL, NULL),
('Leila', 'grous', 'Lac 2', NULL, NULL, NULL, NULL, NULL),
('Hamza hdeibia', 'unitec', 'Hammamet', NULL, NULL, NULL, NULL, NULL),
('Bouslama', 'unitec', 'Bnikhiar', NULL, NULL, NULL, NULL, NULL),
('Ritha', 'centure', 'Centure', NULL, NULL, NULL, NULL, NULL),
('Souhir', NULL, 'unitec', NULL, NULL, NULL, NULL, NULL),
('Fitouri', NULL, 'Hammamet', NULL, NULL, NULL, NULL, NULL),
('Nacer', 'gebsi', 'Hammamet', NULL, NULL, NULL, NULL, NULL),
('Haïfa', 'bnikiar', 'Bnikiar', NULL, NULL, NULL, NULL, NULL),
('Kais', 'moktar', 'Hammamet', NULL, NULL, NULL, NULL, NULL),
('yamen 3ich', 'unitec', 'Hammamet sud', NULL, NULL, NULL, NULL, NULL),
('Mlawhia', 'unitec', 'Nahrawes', NULL, NULL, NULL, NULL, NULL),
('Walid', 'ben lamin', 'Nabeul', NULL, NULL, NULL, NULL, NULL),
('Chiha', NULL, 'Mahersi', NULL, NULL, NULL, NULL, NULL),
('Mahdi', 'unitec', 'Nahrawes', NULL, NULL, NULL, NULL, NULL),
('Hichem', 'brahem', 'Birchalouf', NULL, NULL, NULL, NULL, NULL),
('Slim', 'kayatti', 'Ma3moura', NULL, NULL, NULL, NULL, NULL),
('Fathi', 'besbasia', 'Besbasia', NULL, NULL, NULL, NULL, NULL),
('Montasar ma3moura', 'unitec', 'Nabeul', NULL, NULL, NULL, NULL, NULL),
('Mesri', 'gdira', 'unitec', NULL, NULL, NULL, NULL, 'Hammamet'),
('Tarak ma7louf', 'unitec', 'Ma3moura', NULL, NULL, NULL, NULL, NULL),
('Sami', 'chafi', 'Mahersi', NULL, NULL, NULL, NULL, NULL),
('Kammoun', 'unitec', 'Hammamet', NULL, NULL, NULL, NULL, NULL),
('Hedi Talbi', 'unitec', 'Bouficha', NULL, NULL, NULL, NULL, NULL),
('Mazri gdira', 'unitec', 'Barreket sahel', NULL, NULL, NULL, NULL, NULL),
('Baset', 'chmengui', 'Jusmin', NULL, NULL, NULL, NULL, NULL),
('Assad zmerli', 'unitec', 'Badira', NULL, NULL, NULL, NULL, NULL),
('Nedra hellal', 'unitec', 'Chat souhour', NULL, NULL, NULL, NULL, NULL),
('Fahem', 'unitec', 'Radisson Blu', NULL, NULL, NULL, NULL, NULL),
('Mahdi', 'piscine', 'Afh', NULL, NULL, NULL, NULL, NULL),
('Imed pôle', 'unitec', 'Ma3moura', NULL, NULL, NULL, NULL, NULL),
('Saber sayeh', 'unitec', 'Afh', NULL, NULL, NULL, NULL, NULL),
('Riath Ben thifallah', 'unitec', 'Tazarka', NULL, NULL, NULL, NULL, NULL),
('Med aribi', 'unitec', 'Grombalia, Tunisie', NULL, NULL, NULL, NULL, NULL),
('Achraf juriste', 'unitec', 'Afh', NULL, NULL, NULL, NULL, NULL),
('Gaddour', 'gardaya', 'Gardaya', NULL, NULL, NULL, NULL, NULL),
('Imen', 'Mami', 'Oued Souhil, Tunisie', NULL, NULL, NULL, NULL, NULL),
('Dar', 'rayes', 'Tazarka', NULL, NULL, NULL, NULL, NULL),
('Abd rassek Ben mansour', 'unitec', 'Nabeul', NULL, NULL, NULL, NULL, NULL),
('Rachid', 'haj yahya', 'Hammamet', NULL, NULL, NULL, NULL, NULL),
('Tarak', 'amie', 'Bouagoub', NULL, NULL, NULL, NULL, NULL),
('Hedi', 'maroueni', 'Ma3moura', NULL, NULL, NULL, NULL, NULL),
('Fehmi', 'ben attig', 'Beni Khiar, Tunisie', NULL, NULL, NULL, NULL, NULL),
('Med', 'thwib', 'Bp 224 Hammamet Nord, Hammamet 8050, Tunisie', NULL, NULL, NULL, NULL, NULL),
('Safa', 'massadi', 'unitec', NULL, NULL, NULL, NULL, 'Tazarka'),
('Nabil', 'hammamet', 'Hammamet sud', NULL, NULL, NULL, NULL, NULL),
('Amen Allah', 'unitec', 'Hammamet', NULL, NULL, NULL, NULL, NULL),
('Chiraz', 'mnif', 'Jinen bnikiar', NULL, NULL, NULL, NULL, NULL),
('Salma 09', 'abdmoula', 'Mahersi', NULL, NULL, NULL, NULL, NULL),
('Mohamed', 'skhiri', 'Hammamet', NULL, NULL, NULL, NULL, NULL),
('Omar', 'mabrouk', 'Kraksi', NULL, NULL, NULL, NULL, NULL),
('Monsor', 'unitec', 'Nabeul', NULL, NULL, NULL, NULL, NULL),
('Moez', 'debbich', 'unitec', NULL, NULL, NULL, NULL, 'Menzel Bou Zelfa, Tunisie'),
('Ben taleb', 'unitec', 'Bniwael', NULL, NULL, NULL, NULL, NULL),
('Mohamed', 'riden 1', 'Afh', NULL, NULL, NULL, NULL, NULL),
('Sahbi Ben salha', 'hwaia', 'Hwaria', NULL, NULL, NULL, NULL, NULL),
('Syrine halwi', 'unitec', 'Kraksi', NULL, NULL, NULL, NULL, NULL),
('Marouen', 'Ben salha', NULL, NULL, NULL, NULL, NULL, 'Hwaria'),
('Hamed', 'mbarek', 'Gammart', NULL, NULL, NULL, NULL, NULL),
('Résidence andalouse', 'unitec', 'Afh', NULL, NULL, NULL, NULL, NULL),
('Nejib', 'riden', 'Lido', NULL, NULL, NULL, NULL, NULL),
('Med foued', 'abdmoula', 'Soltane', NULL, NULL, NULL, NULL, NULL),
('Med saied', 'Carrefour', 'Mrezga', NULL, NULL, NULL, NULL, NULL),
('Lotfi', 'mediaword', 'Hammamet', NULL, NULL, NULL, NULL, NULL),
('Ahmed falastini', 'unitec', 'Chraf ribat', NULL, NULL, NULL, NULL, NULL),
('Skandar marzouk', 'unitec', 'Fac de langue', NULL, NULL, NULL, NULL, NULL),
('Ala Haider', 'unitec', 'Mrezga', NULL, NULL, NULL, NULL, NULL),
('Hatem', 'sassi', 'Bir challouf', NULL, NULL, NULL, NULL, 'Nabeul'),
('Med Rafik', 'essid', 'Afh mrezga', NULL, NULL, NULL, NULL, NULL),
('Nejm', 'neffati', 'Jinen Hammamet', NULL, NULL, NULL, NULL, NULL),
('Hammadi', 'haffar', 'Bnikiar', NULL, NULL, NULL, NULL, NULL),
('Hasib', 'terasse', 'Hammamet', NULL, NULL, NULL, NULL, NULL),
('Fares mes onges 1', 'unitec', 'Résident Jeannette', NULL, NULL, NULL, NULL, NULL),
('Tijani', 'unitec', 'Karkouen', NULL, NULL, NULL, NULL, NULL),
('Houssem', 'daoued', 'Salet yassin', NULL, NULL, NULL, NULL, NULL),
('Med saied', 'chotrana', 'Chotrana', NULL, NULL, NULL, NULL, NULL),
('Hichem', 'machat', 'Afh 1', NULL, NULL, NULL, NULL, NULL),
('Med saied', 'karrouba', 'Karrouba', NULL, NULL, NULL, NULL, NULL),
('Med saied', 'bellaleh', 'Afh', NULL, NULL, NULL, NULL, NULL),
('Sami', 'kniwa', 'Mahersi', NULL, NULL, NULL, NULL, NULL),
('Choukri', 'hachada', 'Bnikiar', NULL, NULL, NULL, NULL, NULL),
('Villa espoirs lasad', NULL, 'Hammamet', NULL, NULL, NULL, NULL, NULL),
('Med Saied ahmed', 'saoudi', 'Jinen Hammamet', NULL, NULL, NULL, NULL, NULL),
('Med saied', 'Hay elfawz', 'Jardins d''El Menzah 2, Tunisie', NULL, NULL, NULL, NULL, NULL),
('Med saied jihed', 'majdoub', 'Sidi Mahrsi, Nabeul, Tunisie', NULL, NULL, NULL, NULL, NULL),
('Adnen', 'unitec', 'Al-Maamoura, Tunisie', NULL, NULL, NULL, NULL, NULL),
('Imed Ben Salem', 'unitec', 'Diar Ben Salem, Nabeul', NULL, NULL, NULL, NULL, NULL),
('Anouar trifi', 'unitec', 'El mahersi', NULL, NULL, NULL, NULL, NULL),
('Ritha ben Youssef', NULL, 'Hammamet Sud, Tunisie', NULL, NULL, NULL, NULL, NULL),
('Tarak', 'Hammamet sud', 'Hammamet Sud, Tunisie', NULL, NULL, NULL, NULL, NULL),
('Hedi unitec afh', 'tcs', 'Afh', NULL, NULL, NULL, NULL, NULL),
('Riath', 'kouja', 'Mahersi', NULL, NULL, NULL, NULL, NULL),
('Nejmeddine Mami', 'unitec', 'CH3F+V3V, Hammamet Sud, Tunisie', NULL, NULL, NULL, NULL, NULL),
('Ahmed', 'elect', 'Afh', NULL, NULL, NULL, NULL, NULL),
('Avoramis', 'unitec', 'Hammamet, Tunisie', NULL, NULL, NULL, NULL, NULL),
('Abd Aziz gdara', 'unitec', 'Mornag, Tunisie', NULL, NULL, NULL, NULL, NULL),
('Mahdi', 'toumi', 'Ribat', NULL, NULL, NULL, NULL, NULL),
('Nafaa allam', '1', 'Deux oued', NULL, NULL, NULL, NULL, NULL),
('Hôtel Hammamet beatch', NULL, 'Mrezga, Tunisie', NULL, NULL, NULL, NULL, NULL),
('Achraf tabbel', 'unitec', 'Bnikiar', NULL, NULL, NULL, NULL, NULL),
('Casa', '220', 'Afh 2', NULL, NULL, NULL, NULL, NULL),
('Mourad', 'chaouch', 'Terrain romain', NULL, NULL, NULL, NULL, NULL),
('Sidhom Med', 'ayed', 'Moura', NULL, NULL, NULL, NULL, NULL),
('Tzarka', 'unitec', 'Tazarka, Tunisie', NULL, NULL, NULL, NULL, NULL),
('Fares mes onges 2', 'unitec', 'Resident jannet', NULL, NULL, NULL, NULL, NULL),
('Siryati', 'unitec', 'Afh mresga', NULL, NULL, NULL, NULL, NULL),
('Karima bettayeb', 'unitec', 'Mahersi', NULL, NULL, NULL, NULL, NULL),
('Résidence', 'etta3mir', 'Afh', NULL, NULL, NULL, NULL, NULL),
('Chtiwi', 'unitec', 'Bnikiar', NULL, NULL, NULL, NULL, NULL),
('Fakhri', 'unitec', 'Bir Bou Rekba, Tunisie', NULL, NULL, '23720309', NULL, NULL),
('Med lotfi', 'monchar', 'Monchar', NULL, NULL, NULL, NULL, NULL),
('Med saied', 'birboutagba', 'Bir Bou Rekba, Tunisie', NULL, NULL, NULL, NULL, NULL),
('Med ben Slimane', NULL, 'Al-Maamoura, Tunisie', NULL, NULL, NULL, NULL, NULL),
('Anis', 'riahi', 'Mornag, Tunisie', NULL, NULL, NULL, NULL, NULL),
('Hôtel impérial', 'unitec', 'Hammamet sud', NULL, NULL, NULL, NULL, NULL),
('Med saied', 'geddana', 'Resident jannet', NULL, NULL, NULL, NULL, NULL),
('Nadra hellal', 'moura', 'Moura', NULL, NULL, NULL, NULL, NULL),
('Wajdi', 'fnina', 'Hammamet sud', NULL, NULL, NULL, NULL, NULL),
('Lasaad', 'gardien', 'Hammamet', NULL, NULL, NULL, NULL, NULL),
('Linda', 'chalbi', 'Maamoura', NULL, NULL, NULL, NULL, NULL),
('Salwa morjen', 'zagouen', 'Zaghouan, Tunisie', NULL, NULL, NULL, NULL, NULL),
('Zouhair', 'promoteurs', 'Karrouba mresga', NULL, NULL, NULL, NULL, NULL),
('Résidence la perla', 'unitec', 'Afh mresga', NULL, NULL, NULL, NULL, NULL),
('Nadra hellal', 'chatzouhour', 'Chat zouhour', NULL, NULL, NULL, NULL, NULL),
('Hmila', 'tarek', 'Mahersi', NULL, NULL, NULL, NULL, NULL),
('Moh henchir', 'koret', NULL, NULL, NULL, NULL, NULL, NULL),
('Mohamed', 'bechwika', 'Sidi hammed', NULL, NULL, NULL, NULL, NULL),
('Makki', 'client', 'Lido', NULL, NULL, NULL, NULL, NULL),
('Lotfi Ben Hamouda', NULL, 'Nabeul, Tunisie', NULL, NULL, NULL, NULL, NULL),
('Nour', 'meridiana', 'Résidence Meridiana, Nabeul, Tunisie', NULL, NULL, NULL, NULL, NULL),
('Diar Fafa', 'unitec', 'Kélibia, Tunisie', NULL, NULL, NULL, NULL, NULL),
('Oula market mestiri', 'khadem', 'Moura', NULL, NULL, NULL, NULL, NULL),
('Nesrine', 'fkih', 'Sidi Slimane, Maroc', NULL, NULL, '24765027', NULL, 'Nabeul'),
('Med', 'galleb', 'Mahersi', NULL, NULL, NULL, NULL, NULL),
('Imed', 'awnallah', 'Afh', NULL, NULL, NULL, NULL, NULL),
('Fahd lwati somaa', 'unitec', 'Somaa', NULL, NULL, NULL, NULL, NULL),
('Oued lesoued', 'unitec', 'Oued Lassoued, Bir Bouregba, Tunisie', NULL, NULL, NULL, NULL, NULL),
('Hafeth', 'triki', 'Afh2', NULL, NULL, NULL, NULL, NULL),
('Aymen magraoui', 'unitec', 'Mahersi', NULL, NULL, NULL, NULL, NULL),
('Fethi Med', 'monchar', 'Monchar', NULL, NULL, NULL, NULL, NULL),
('Antonio', 'unitec', 'Afh', NULL, NULL, NULL, NULL, NULL),
('Marouen chawachi', 'diamand', 'Karrouba', NULL, NULL, NULL, NULL, NULL),
('Hichem ahres', 'makki', 'Bouficha', NULL, NULL, NULL, NULL, NULL),
('Med saied iheb', 'mehrez', 'Karrouba', NULL, NULL, NULL, NULL, NULL),
('Bechwika', 'maison', 'Kraksi', NULL, NULL, NULL, NULL, NULL),
('Khaled chemli', 'archi', 'Ariana', NULL, NULL, NULL, NULL, NULL),
('Bizanse', NULL, 'Nabeul', NULL, NULL, NULL, NULL, NULL),
('Mouldi', 'issa', 'Terrain erromain', NULL, NULL, NULL, NULL, NULL),
('Mohamed zine', 'unitec', 'Mahersi', NULL, NULL, NULL, NULL, NULL),
('Monsef mbarek', 'fils2', 'Mahersi', NULL, NULL, NULL, NULL, NULL),
('Zied', 'unitec', 'Mimosa', NULL, NULL, NULL, NULL, NULL),
('Malika Amel', 'unitec', 'Meznin', NULL, NULL, NULL, NULL, NULL),
('Jalila', 'maamouri', 'Mahersi', NULL, NULL, NULL, NULL, NULL),
('Nordine goul', 'unitec', 'Mresga', NULL, NULL, NULL, NULL, NULL),
('Klibia régulateur', 'unitec', 'Klibia', NULL, NULL, NULL, NULL, NULL),
('Gannar', 'unitec', 'Hammamet', NULL, NULL, NULL, NULL, NULL),
('Othmane afh', 'unitec', 'Afh', NULL, NULL, NULL, NULL, NULL),
('Kamel fourati', 'unitec', 'Mahersi', NULL, NULL, NULL, NULL, NULL),
('Adel', 'tletli', 'Mahersi', NULL, NULL, NULL, NULL, NULL),
('Karim arfaoui', 'unitec', 'Grombalia, Tunisie', NULL, NULL, NULL, NULL, NULL),
('Karim ayed', 'unitec', 'Kraksi', NULL, NULL, NULL, NULL, NULL),
('Tayeb', 'felfel', 'Dar elweli', NULL, NULL, NULL, NULL, NULL),
('Nabil', 'somrani', 'Grombalia', NULL, NULL, NULL, NULL, NULL),
('Ahmed', 'elabed', 'Bnikhiar', NULL, NULL, NULL, NULL, NULL),
('Selim', 'lahkdar', 'Tunis', NULL, NULL, NULL, NULL, NULL),
('Kantaoui', 'unitec', 'Kantaoui, Hammam Sousse, Tunisie', NULL, NULL, NULL, NULL, NULL),
('Kais Hammamet', 'unitec', 'CH3F+V3V, Hammamet Sud, Tunisie', NULL, NULL, NULL, NULL, NULL),
('Med Nakkach', 'Hammamet', 'Galaxy Hammamet', NULL, NULL, NULL, NULL, NULL),
('Hsan Bilel gdara', 'unitec', 'Afh', NULL, NULL, NULL, NULL, NULL),
('Fawzi', 'drissi', 'Hammamet Sud, Tunisie', NULL, NULL, NULL, NULL, NULL),
('Habib', 'dridi', 'Jinen bnikhiar', NULL, NULL, NULL, NULL, NULL),
('Med saied', 'hammem lif', 'Hammam Lif, Tunisie', NULL, NULL, NULL, NULL, NULL),
('Faten', 'Costa marina', 'Afh', NULL, NULL, NULL, NULL, NULL),
('Mouldi', 'lahmar', 'Mahersi', NULL, NULL, NULL, NULL, NULL),
('Mahdi chalgoum', 'unitec', 'Tunis Hay el fawz', NULL, NULL, NULL, NULL, NULL),
('Ritha terrain rommain', NULL, 'Terrain erromain', NULL, NULL, NULL, NULL, NULL),
('Rabi3', 'daoued', 'Afh', NULL, NULL, NULL, NULL, NULL),
('Karim', 'Afh', 'Afh', NULL, NULL, NULL, NULL, NULL),
('Résidence polvare', 'unitec', 'Afh', NULL, NULL, NULL, NULL, NULL),
('Hôte venus', 'unitec', 'Hammamet, Tunisie', NULL, NULL, NULL, NULL, NULL),
('Nabil berrached', 'unitec', 'Cité mora', NULL, NULL, NULL, NULL, NULL),
('Khaled l''agha', 'unitec', 'Hammamet ribat', NULL, NULL, NULL, NULL, NULL),
('Kamel ben hsin', NULL, 'Mornag, Tunisie', NULL, NULL, NULL, NULL, NULL),
('Med swissi', 'ribat', 'Ribat Hammamet', NULL, NULL, NULL, NULL, NULL),
('Aymen magraoui', 'unitec', 'Mresga', NULL, NULL, NULL, NULL, 'chokri sallawi'),
('Raoutha', 'kooli', 'Hammamet, Tunisie', NULL, NULL, '26227153', NULL, NULL),
('Ahmed abed', '2', 'Afh 2', NULL, NULL, NULL, NULL, NULL),
('Mounir', 'nouma', 'Mahersi', NULL, NULL, NULL, NULL, NULL),
('Hichem', 'jaszi', 'Cleub med', NULL, NULL, NULL, NULL, NULL),
('Adem', 'riden', 'Afh 2', NULL, NULL, NULL, NULL, NULL),
('Hamida', 'mrabet', 'Besbasia', NULL, NULL, NULL, NULL, NULL),
('Aymen magraoui', '3', 'Ribat Hammamet', NULL, NULL, NULL, NULL, 'Solde: 3000.500'),
('Amin Fathi', 'client', 'CH5R+PX, Hammamet Sud, Tunisie', NULL, NULL, NULL, NULL, NULL),
('Mounia', 'yakouta', 'Hammamet', NULL, NULL, NULL, NULL, NULL),
('Khaled agha', '2', 'Chraf Hammamet', NULL, NULL, NULL, NULL, NULL),
('Med saied', 'barreka', 'Barreket essahel', NULL, NULL, NULL, NULL, NULL),
('Korba', 'unitec', 'Korba', NULL, NULL, NULL, NULL, NULL),
('Walid garbi', 'unitec', 'Bouficha, Tunisie', NULL, NULL, NULL, NULL, NULL),
('Salma', 'garali', 'Mimosa', NULL, NULL, NULL, NULL, NULL),
('Hanen', 'gannouchi', 'Monchar Hammamet', NULL, NULL, NULL, NULL, NULL),
('Med saied', 'klibia', 'Klibia', NULL, NULL, NULL, NULL, NULL),
('Trabelsi', 'fathi', 'Afh 2', NULL, NULL, NULL, NULL, NULL),
('Med', 'nakbou', 'Afh', NULL, NULL, NULL, NULL, NULL),
('Liesse', 'maher', 'Bnikiar', NULL, NULL, NULL, NULL, NULL),
('Zied', 'ben gabsia', 'Cité moura', NULL, NULL, NULL, NULL, NULL),
('Casa', '218', 'Afh', NULL, NULL, NULL, NULL, NULL),
('Kalfallah', 'cascade', 'Hanchir kort', NULL, NULL, NULL, NULL, NULL),
('Wethek', 'zouawi', 'Mahersi', NULL, NULL, NULL, NULL, NULL),
('Rayen chrif case', '427', 'Afh 2', NULL, NULL, NULL, NULL, NULL),
('Med saied', 'degaz', 'École primaire', NULL, NULL, NULL, NULL, NULL),
('Med', 'Kacem', 'Clinique Amen', NULL, NULL, NULL, NULL, NULL),
('Mehdi', 'korba', 'Korba', NULL, NULL, NULL, NULL, NULL),
('Sahbi bchir', 'unitec', 'Mresga', NULL, NULL, NULL, NULL, NULL),
('Aymen dakno', 'unitec', 'Mahersi', NULL, NULL, NULL, NULL, NULL),
('Nordine', 'Zouhair', 'Hammamet ville', NULL, NULL, NULL, NULL, NULL),
('Hager', 'tazaka', 'Tazarka', NULL, NULL, '97607562', NULL, NULL),
('Farid', NULL, 'Hammamet Sud, Tunisie', NULL, NULL, '21313355', NULL, NULL),
('Rayen chrif', '2', 'Afh', NULL, NULL, NULL, NULL, NULL),
('Hôtel solario', 'unitec', 'Hammamet sud', NULL, NULL, NULL, NULL, NULL),
('Marouane chaouachi', 'maison', 'Karroba', NULL, NULL, NULL, NULL, NULL),
('Amin', 'abdslam', 'Hwaria Nabeul', NULL, NULL, NULL, NULL, NULL),
('Sidi Hamed', 'unitec', 'Sidi Hamed', NULL, NULL, NULL, NULL, NULL),
('Sami', 'chedly', 'Résidence karam', NULL, NULL, NULL, NULL, NULL),
('Khalfallah', 'afh', 'Afh 2', NULL, NULL, NULL, NULL, NULL),
('Med saied klibia', '2', 'Klibia', NULL, NULL, NULL, NULL, NULL),
('Med saied', 'Oued lewed', 'Oued leswed', NULL, NULL, NULL, NULL, NULL),
('Ayda', 'taliani', 'Terrain romain', NULL, NULL, NULL, NULL, NULL),
('Hmaida', 'unitec', 'Mahersi', NULL, NULL, NULL, NULL, NULL),
('Bella marina', 'unitec', 'Sidi hammed', NULL, NULL, NULL, NULL, NULL),
('Khaled', 'korbi', 'Hammamet', NULL, NULL, NULL, NULL, NULL),
('Khaled', 'swiss', 'Mida', NULL, NULL, NULL, NULL, NULL),
('Selim', 'mrabet', 'Mahersi', NULL, NULL, NULL, NULL, NULL),
('Houda', 'ben saad', 'Lebna', NULL, NULL, NULL, NULL, NULL),
('Arous', 'unitec', 'Daroufa', NULL, NULL, NULL, NULL, NULL),
('Lamjed', 'hsiki', 'Citée mora', NULL, NULL, '20357095', NULL, NULL),
('Mourad', 'bayoub', 'Hanchir kort', NULL, NULL, NULL, NULL, NULL),
('Honda', 'bouslama', 'Bnikhiar', NULL, NULL, NULL, NULL, NULL),
('Aziz', 'bougattef', 'Jinen Hammamet', NULL, NULL, '52595252', NULL, NULL),
('Lobna Cherif', 'unitec', 'Somaa', NULL, NULL, NULL, NULL, NULL),
('Mzabi Aymen', 'mezouel', 'Badira', NULL, NULL, NULL, NULL, NULL),
('Mouldi', 'Benhaha', 'Oued souhil', NULL, NULL, '98308750', NULL, NULL),
('Najd waili', 'unitec', 'Terrain romain', NULL, NULL, NULL, NULL, NULL),
('Résidence', 'tiba', 'Afh', NULL, NULL, NULL, NULL, NULL),
('Maher', '1', 'Bnikhiar', NULL, NULL, NULL, NULL, NULL),
('Si Mohammed', 'mrabet', 'Mahersi', NULL, NULL, NULL, NULL, NULL),
('Gaddour bni khiar', NULL, 'Jinen bnikhiar', NULL, NULL, NULL, NULL, NULL),
('Hajer', 'tazarka', 'Tazarka', NULL, NULL, NULL, NULL, NULL),
('Hanen', 'kattar', 'Bir challuf', NULL, NULL, NULL, NULL, NULL),
('Lotfi', 'abdkhalek', 'Lido', NULL, NULL, NULL, NULL, NULL),
('Hedi', 'saadaoui', 'Hammamet', NULL, NULL, NULL, NULL, NULL),
('Bilel setti', 'bnikhiar', 'Bnikhiar', NULL, NULL, NULL, NULL, NULL),
('Lamjed', 'ben gorbel', 'Afh', NULL, NULL, NULL, NULL, NULL),
('Rafiaa', 'mostafa', 'Mahersi', NULL, NULL, NULL, NULL, NULL),
('Khaled lefkhih', 'unitec', 'Nabeul', NULL, NULL, NULL, NULL, NULL),
('Nadia', 'amel', 'Mahersi', NULL, NULL, NULL, NULL, NULL),
('Fathi', 'bniwael', 'Bniwaell', NULL, NULL, NULL, NULL, NULL),
('Mohamed', 'chalbi', 'Mahersi', NULL, NULL, NULL, NULL, NULL),
('Bilel gdara', 'daroufa', 'Daroufa', NULL, NULL, NULL, NULL, NULL),
('Nader jmaa', 'Bilel gdara', 'Moura', NULL, NULL, NULL, NULL, NULL),
('Med Hatta', 'Oued lesoued', 'Oued lesoued', NULL, NULL, NULL, NULL, NULL),
('Mohamed', 'riden 5', 'Afh', NULL, NULL, NULL, NULL, NULL),
('Piscine', 'somaa', 'Somaa', NULL, NULL, NULL, NULL, NULL),
('Nordine Zouhair', '2', 'Bir chab3a bniwael', NULL, NULL, NULL, NULL, NULL),
('Adem Belhadj hsine', '2', 'Afh', NULL, NULL, NULL, NULL, NULL),
('Jalel', 'bnikhiar', 'Bnikhiar', NULL, NULL, NULL, NULL, NULL),
('Fawzi entrepreneur', '2', 'San ville', NULL, NULL, NULL, NULL, NULL),
('Mourad', 'mzid', 'Kraksi', NULL, NULL, NULL, NULL, NULL),
('Basma', 'wed errih', 'Oued errih', NULL, NULL, NULL, NULL, NULL),
('Mooataz hbib', 'ribat', 'Ribat chraf', NULL, NULL, '27700143', NULL, NULL),
('Bilel setti', 'weslati', 'Weslati', NULL, NULL, NULL, NULL, NULL),
('Adlene', 'thehbi', 'Kraksi', NULL, NULL, '98331894', NULL, NULL),
('Monther', 'zneidi', 'Karkouen', NULL, NULL, NULL, NULL, NULL),
('Marouen saheb', 'liesse', 'Bnikhiar', NULL, NULL, NULL, NULL, NULL),
('Riden', 'duplex', 'Afh', NULL, NULL, NULL, NULL, NULL),
('Med swissi', 'ihsan', 'Ihsen', NULL, NULL, NULL, NULL, NULL),
('Monther', 'jinen Hammamet', 'Jinen Hammamet', NULL, NULL, NULL, NULL, NULL),
('Mooataz', 'diar ben salem', 'Diar ben salem', NULL, NULL, NULL, NULL, NULL),
('Wael riden', 'maison', 'Afh', NULL, NULL, NULL, NULL, NULL),
('Bilel gdara', 'leknaies', 'Knayes', NULL, NULL, NULL, NULL, NULL),
('Samia', 'hrichi', 'Mahersi', NULL, NULL, NULL, NULL, NULL),
('Gaddour', 'jasmin', 'Jasmin', NULL, NULL, NULL, NULL, NULL),
('Hammadi unitec', 'bnikhiar', 'Bnikhiar', NULL, NULL, NULL, NULL, NULL),
('Résidence port yesmine', 'unitec', 'Yasmin Hammamet, Tunisie', NULL, NULL, NULL, NULL, NULL),
('Walid ajmi', 'frère', 'Mresgua violette', NULL, NULL, NULL, NULL, NULL),
('Maison tazarka', 'unitec', 'Tazarka', NULL, NULL, NULL, NULL, NULL),
('Sofie', 'ne gozia', 'Africadjad korba', NULL, NULL, NULL, NULL, NULL),
('Aymen wed leswed', '2', 'Oued leswed', NULL, NULL, NULL, NULL, NULL),
('Nacer entre', 'unitec', 'Barraket essahel', NULL, NULL, NULL, NULL, NULL),
('Mehdi jaziri', 'unitec', 'Bnikhiar', NULL, NULL, NULL, NULL, NULL),
('Mouna daoued', 'unitec', 'Douikla', NULL, NULL, NULL, NULL, NULL),
('Hamdi', 'zouawi', 'Bnikhiar', NULL, NULL, NULL, NULL, NULL),
('Badreddine', 'elbach', 'Ramses', NULL, NULL, NULL, NULL, NULL),
('Mohamed', 'houasse', 'Mahersi', NULL, NULL, NULL, NULL, NULL),
('Ramzi', 'chichi', 'Afh2', NULL, NULL, NULL, NULL, NULL),
('Mahmoud', 'korba', 'Korba', NULL, NULL, NULL, NULL, NULL),
('Gaddour bnikhiar', '2', 'Bnikhiar', NULL, NULL, NULL, NULL, NULL),
('Mouriss', NULL, 'Mamoura', NULL, NULL, NULL, NULL, NULL),
('Moussif', 'bnikhiar', 'Bnikhiar', NULL, NULL, NULL, NULL, NULL),
('Makram', 'takelsa', 'Takelsa', NULL, NULL, NULL, NULL, NULL),
('Anis', 'dammak', 'Mresgua', NULL, NULL, NULL, NULL, NULL),
('Chabbouh', 'lido', 'Lido', NULL, NULL, NULL, NULL, NULL),
('Fatma', 'bouzid', 'Soltan', NULL, NULL, NULL, NULL, NULL),
('Lasaad ben Abdallah', 'unitec', 'Rambla Hammamet', NULL, NULL, NULL, NULL, NULL),
('Himrit', 'walid', 'Oued souhil', NULL, NULL, NULL, NULL, NULL),
('Abd razak', 'unitec', 'Mresgua unitec', NULL, NULL, NULL, NULL, NULL),
('Jrad', NULL, 'Besbasia', NULL, NULL, NULL, NULL, NULL);
